twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/errors.html.twig'
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_name: 'User Management'
        current_year: "'now'|date('Y')"
when@test:
    twig:
        strict_variables: true
